### ISSUE TITLE
no varible for colors

### ISSUE THREAD

**Issue by juanlramos** [Thealaskage/UniqueTrip-LandingPage#1]
Nice landing page, i was analizing your code and i saw that you used the name of all color and hexadeciamal code in every elements, it would be better if you have used variable for colors, it's better for maintenance. i'm studying how to contribute with another developer, i can fix it for you if you want.

**Comment by Thealaskage** [comment]
Sure, thank you for the feedback. I would appreciate it if you could help me :).
